### ISSUE TITLE
What do you mean in step 10 of your guide for setting up your own website?

### ISSUE THREAD

**Issue by le-bananafish** [jmcglone/jmcglone.github.io#3]
You say to update index.html to use your default layout. By this do you mean replace the entire document or just a section?

**Comment by jmcglone** [comment]
In step 3 you create the first iteration of the `index.html` file that does not use Jekyll's template system. In step 9, you create the `_layouts/default.html` template file, which includes elements that repeat on all your website's pages (such as the head, site navigation, and footer). For each page that calls the default template in the front matter, the `{{ content }}` liquid tag in `_layouts/default.html` will read/write any content after the front matter.

So in step 10, the idea is to update `index.html` by replacing the entire contents of the file to use your default template. You don't need the head, navigation, or footer that was previously in there, because that markup is now included in the default template. So replace the entirety of `index.html` with this code: 

```
---
layout: default
title: Hank Quinlan, Horrible Cop
---
<div class="blurb">
    <h1>Hi there, I'm Hank Quinlan!</h1>
    <p>I'm best known as the horrible cop from <em>A Touch of Evil</em> Don't trust me. <a href="/about">Read more about my life...</a></p>
</div><!-- /.blurb -->

```

Hope this helps and thanks for your question!

**Comment by jmcglone** [comment]
Also, I've clarified step 10 based on your question. Thanks!

**Comment by le-bananafish** [comment]
Thank you very much for the clear up!

**Comment by le-bananafish** [comment]
I also have another question. I followed your steps for creating a blog but it doesn't work. Whenever I click on the link, it goes error 404

**Comment by le-bananafish** [comment]
Actually I'll just try and fix it myself. Sorry for the troubles.
